// src/examples/signin/SigninCard.tsx
import React, { ReactNode, useState } from "react";
import SigninForm from "./SigninForm";
import SocialSigninButton from "./components/SocialSigninButton";
import { Helmet } from "react-helmet";
import { Alert } from "@material-ui/lab";
import SeparateLineWithText from "./components/SeparateLineWithText";
import styles from "./SigninCard.module.scss";
import { RequestStatus } from "./enum/request.enum";

interface SigninFormDto {
  email: string;
  password: string;
}

const SigninPage = () => {
  const [data, setData] = useState({
    response: null,
    error: null,
    errorFields: null,
    status: RequestStatus.Nop,
  });

  const onSubmit = async (data: SigninFormDto) => {
    try {
      setData({
        response: null,
        error: null,
        errorFields: null,
        status: RequestStatus.Loading,
      });
      setTimeout(() => {
        // Http Request
      }, 2000);
    } catch (error) {
      setData({
        response: null,
        error: error?.message,
        errorFields: error?.errors,
        status: RequestStatus.Error,
      });
    }
    return data;
  };

  return (
    <>
      <Helmet>
        <title>SignIn Page</title>
      </Helmet>
      <PageContainer>
        <CardContainer>
          <AppLogo />
          <PageTitle />
          <AppFormContainer>
            {data.error && (
              <Alert severity="error" className={styles.errorAlert}>
                {data.error}
              </Alert>
            )}
            <SigninForm message="Sign up" onSubmit={onSubmit}></SigninForm>
          </AppFormContainer>

          <SeparateLineWithText text="OR" />
          <SocialSignin />
        </CardContainer>
      </PageContainer>
    </>
  );
};

interface AppFormContainerProps {
  children: ReactNode;
}

const AppFormContainer = ({ children }: AppFormContainerProps) => {
  return <div className={styles.form}>{children}</div>;
};

const PageTitle = () => {
  return (
    <div className={styles.pageTitle}>
      <div className={styles.title}>Signin to:</div>
      <div className={styles.subtitle}>Accounting</div>
    </div>
  );
};

const AppLogo = () => {
  return (
    <div className={styles.appLogo}>
      <img
        className={styles.logoImg}
        src="/assets/images/signin/logo-white.png"
      />
      <h2 className={styles.title}>ABugLife Studio</h2>
    </div>
  );
};

interface PageContainerProps {
  children: ReactNode;
}
const PageContainer = ({ children }: PageContainerProps) => {
  return (
    <div className={styles.page}>
      <div className={styles.bgBelow}></div>
      <div className={styles.bgUpper}></div>
      <div className={styles.bgColorOverlay}></div>
      <div className={styles.pageBody}>{children}</div>
    </div>
  );
};

interface CardContainerProps {
  children: ReactNode;
}
const CardContainer = ({ children }: CardContainerProps) => {
  return (
    <div className={styles.card}>
      <div className={styles.cardInner}>{children}</div>
    </div>
  );
};

const SocialSignin = () => {
  return (
    <div className={styles.socialSigninContainer}>
      <SocialSigninButton
        text="Signin with Google"
        logo="/assets/images/social/google.png"
        type="button"
      />

      <SocialSigninButton
        text="Signin with Line"
        logo="/assets/images/social/line.png"
        type="button"
      />

      <SocialSigninButton
        text="Signin with Microsoft"
        logo="/assets/images/social/microsoft.png"
        type="button"
      />
    </div>
  );
};

export default SigninPage;

// snippets/angular/src/app/signin/signin-card/signin-card.component.ts
import { HttpClient } from '@angular/common/http';
import { Component, OnInit } from '@angular/core';
import { RequestStatus } from 'src/app/enum/request-status.enum';

@Component({
  selector: 'app-signin-card',
  templateUrl: './signin-card.component.html',
  styleUrls: ['./signin-card.component.scss']
})
export class SigninCardComponent implements OnInit {

  status: number = RequestStatus.Nop;
  RequestStatus = RequestStatus;
  error: string = null;

  constructor(
    private http: HttpClient
  ) { }

  ngOnInit(): void {
  }

  async onSubmit(dto) {
    this.status = RequestStatus.Loading;
    try {
      // Http Request
      setTimeout(() => {
        this.status = RequestStatus.Error;
        this.error = `Username or password is incorrect`;
      }, 2000)
    } catch (error) {
      this.status = RequestStatus.Error;
      this.error = error;
    }
  }

}

<div class="page">
  <div class="bg-below"></div>
  <div class="bg-color-overlay"></div>
  <div class="page-body">
    <div class="card-container">
      <div class="card">
        <div class="card-body">
          <div class="app-logo">
            <img class="logo-img" src="/assets/images/signin/logo-white.png" />
            <h2 class="title">ABugLife Studio</h2>
          </div>
          <div class="page-title">
            <div class="title">Signin to:</div>
            <div class="subtitle">Accounting</div>
          </div>
          <div class="form">
            <ng-container *ngIf="status === RequestStatus.Error">
              <div class="alert">
                {{error}}
              </div>
            </ng-container>
            <app-signin-form 
              [status]="status"
              (onFormSubmit)="onSubmit($event)">
            </app-signin-form>
          </div>

          <app-separate-line-with-text text="OR"></app-separate-line-with-text>

          <div class="social-signin-container">
            <app-button-social-signin text="Signin with Google" logo="/assets/images/social/google.png">
            </app-button-social-signin>
            <app-button-social-signin text="Signin with Line" logo="/assets/images/social/line.png">
            </app-button-social-signin>
            <app-button-social-signin text="Signin with Microsoft" logo="/assets/images/social/microsoft.png">
            </app-button-social-signin>
          </div>
        </div>
      </div>
    </div>
    <div class="footer">
      <div class="footer-link-container">
        <div class="link">Privacy Policy</div>
        <div class="dot">•</div>
        <div class="link">User Notice</div>
      </div>
      <div class="copy-right">
        @ 2021 ABugLife Studio, Inc. All rights reserved
      </div>
    </div>
  </div>
</div>
