// src/examples/signin/SocialSigninButton.tsx
/** @jsx jsx */
import { css, jsx } from '@emotion/react'
import React, { useState } from 'react';
import tw from 'twin.macro';
import PulseLoader from "react-spinners/PulseLoader";
import { Button } from '@material-ui/core';

interface ButtonLoadingProps {
    isLoading?: boolean,
    text: string,
    logo?: string,
    type?: "button" | "submit" | "reset",
}

export default function SocialSigninButton({ isLoading, text, logo, type = 'button' }: ButtonLoadingProps) {

    const submitBtnStyle = css`
        ${tw`rounded relative text-primary bg-white uppercase font-bold border-none py-3 h-auto flex items-center justify-center w-full h-12 shadow`}

        .label {
            ${tw`flex-1 text-gray-600`}
        }
        &:hover, &:focus {
            ${tw`bg-gray-100 text-gray-700 shadow-md`}
        }
    `

    return (
        <Button type={type} css={submitBtnStyle} variant="contained">
            <img
              className="mx-auto h-8 w-8"
              src={logo}
            />
            <div className="label">{text}</div>
        </Button>
    )
}

// snippets/vue/src/components/button/SocialSigninButton.vue
<template>
  <v-btn :type="type" class="button" color="">
    <img class="logo-img" :src="logo" />
    <div class="label">{{text}}</div>
  </v-btn>
</template>


<script lang="ts">
export default {
  props: {
    isLoading: Boolean,
    text: String,
    logo: String,
    type: String,
  },
};
</script>

<style lang="scss" scoped>
.button {
  @apply rounded relative text-primary bg-surface uppercase font-bold py-0 flex items-center justify-center w-full h-12 shadow border border-solid border-outline px-3 mb-2 text-sm tracking-wider;
  height: var(--button-height);

  &::v-deep {
    .v-btn__overlay {
      @apply bg-background opacity-5;
    }

    .v-ripple__container {
      @apply bg-background opacity-5;
    }
  }

  .label {
    @apply flex-1 text-on-surface;
  }

  .logo-img {
    @apply mx-auto h-8 w-8;
  }

  &:hover,
  &:focus {
    @apply bg-background text-on-background shadow-md;
  }
}
</style>
