// snippets/vue/src/pages/signin/SigninForm.vue
<template>
  <Form @submit="onSubmit" :validation-schema="schema">
    <div class="form">
      <app-input
        name="email"
        icon="account-box-outline"
        placeholder="abc@gmail.com"
      />
      <app-input
        name="password"
        icon="key-outline"
        placeholder="password"
        type="password"
      />

      <div class="additional-container">
        <a class="link" href="/forgot-password">Forgot Password?</a>
        <a class="link" href="/register">Create Account</a>
      </div>

      <app-loading-button
        :isLoading="status === RequestStatus.Loading"
        type="submit"
        text="Signin"
      />
    </div>
  </Form>
</template>

<script lang="ts">
import { Form } from "vee-validate";
import * as Yup from "yup";
import { RequestStatus } from "@/enum/request-status.enum";

export default {
  props: {
    status: RequestStatus,
  },
  data() {
    return {
      RequestStatus,
    };
  },
  emits: ["on-submit"],
  components: {
    Form,
  },
  setup(props, context) {
    function onSubmit(values: any) {
      context.emit("on-submit", values);
    }
    const schema = Yup.object().shape({
      email: Yup.string().required(),
      password: Yup.string().required(),
    });

    return {
      onSubmit,
      schema,
    };
  },
};
</script>

<style lang="scss" scoped>
.form {
  @apply mb-10;
}

.additional-container {
  @apply flex items-center justify-between mb-6 py-0;

  .link {
    @apply text-sm text-on-surface opacity-50;

    &:hover {
      @apply opacity-100;
    }
  }
}
</style>

// snippets/angular/src/app/signin/signin-form/signin-form.component.ts
import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { FormBuilder, FormGroup } from '@angular/forms'
import { RequestStatus } from 'src/app/enum/request-status.enum';

@Component({
  selector: 'app-signin-form',
  templateUrl: './signin-form.component.html',
  styleUrls: ['./signin-form.component.scss']
})
export class SigninFormComponent implements OnInit {
  @Input() error: string;
  @Input() status: RequestStatus = null;
  @Output() onFormSubmit: EventEmitter<any> = new EventEmitter();
  RequestStatus = RequestStatus;

  form: FormGroup;

  constructor(
    private http: HttpClient,
    private fb: FormBuilder
  ) { }

  ngOnInit(): void {
    this.form = this.fb.group({
      username: '',
      password: ''
    })
  }

  onSubmit() {
    if (!this.form.valid) {
      this.form.markAsTouched()
      return false;
    }
    this.onFormSubmit.emit(this.form.value)
  }
}

<form class="app-login" [formGroup]="form" (submit)="onSubmit()">
  <div class="form-container">
    <form-input placeholder="abc@gmail.com" [required]="true" formControlName="username" type="text" name="username"
      [required]="true" [touched]="form.touched" icon="person_outline">
    </form-input>
    <form-input placeholder="Password" [required]="true" formControlName="password" type="password" name="password"
      [required]="true" [touched]="form.touched" icon="lock_open">
    </form-input>
  </div>
  <div class="additional-container">
    <a class="link" href="/forgot-password">Forgot Password?</a>
    <a class="link" href="/register">Create Account</a>
  </div>
  <app-button-loading [isLoading]="status == RequestStatus.Loading" type="submit" text="Sign In"></app-button-loading>
</form>
