// snippets/vue/src/components/button/AppLoadingButton.vue
<template>
  <v-btn :type="type" class="button" color="">
    <div class="label">{{text}}</div>
  </v-btn>
</template>


<script lang="ts">
export default {
  props: {
    isLoading: Boolean,
    text: String,
    type: String,
  },
};
</script>

<style lang="scss" scoped>
.button {
  @apply rounded relative text-on-primary bg-primary uppercase font-bold border-none py-3 flex items-center justify-center w-full h-12 shadow px-3 mb-2 text-sm;
  height: var(--button-height);

  &::v-deep {
    .v-btn__overlay {
      @apply bg-primary opacity-5;
    }

    .v-ripple__container {
      @apply bg-primary opacity-5;
    }
  }

  .label {
    @apply flex-1 text-on-primary;
  }

  .logo-img {
    @apply mx-auto h-8 w-8;
  }

  &:hover,
  &:focus {
    @apply bg-primary text-on-primary shadow-md;
  }
}
</style>

// src/examples/signin/AppLoadingButton.tsx
/** @jsx jsx */
import { css, jsx } from '@emotion/react'
import React, { useState } from 'react';
import tw from 'twin.macro';
import PulseLoader from "react-spinners/PulseLoader";
import { Button } from '@material-ui/core';

interface ButtonLoadingProps {
    isLoading: boolean,
    text: string,
    type?: "button" | "submit" | "reset",
}

export default function AppButtonLoading({ isLoading, text, type = 'button' }: ButtonLoadingProps) {

    const submitBtnStyle = css`
        ${tw`rounded relative text-white bg-green-500 uppercase font-bold border-none py-3 h-auto flex items-center justify-center w-full h-12 shadow`}
        &:hover, &:focus {
            ${tw`bg-green-600 text-white shadow-lg`}
        }
    `

    return (
        <Button type={type} css={submitBtnStyle} variant="contained">
            <PulseLoader color={'#FFF'} loading={isLoading} size={8} />
            { !isLoading && <div className="label">{text}</div> }
        </Button>
    )
}
