// snippets/vue/src/pages/signin/Signin.vue
<template>
  <div class="page">
    <div class="bg-below"></div>
    <div class="bg-color-overlay"></div>
    <div class="page-body">
      <div class="card-container">
        <div class="card">
          <div class="card-inner">
            <div class="app-logo">
              <img
                class="logo-img"
                src="/assets/images/signin/logo-white.png"
              />
              <h2 class="title">ABugLife Studio</h2>
            </div>
            <div class="page-title">
              <div class="title">Signin to:</div>
              <div class="subtitle">Accounting</div>
            </div>
            <div class="alert" v-if="status === RequestStatus.Error">
              {{ error }}
            </div>
            <signin-form :status="status" @on-submit="onSubmit"/>

            <separate-line-with-text text="OR" />

            <div class="social-signin-container">
              <social-signin-button
                text="Signin with Google"
                logo="/assets/images/social/google.png"
                type="button"
              />

              <social-signin-button
                text="Signin with Line"
                logo="/assets/images/social/line.png"
                type="button"
              />

              <social-signin-button
                text="Signin with Microsoft"
                logo="/assets/images/social/microsoft.png"
                type="button"
              />
            </div>
          </div>
        </div>
      </div>
      <div class="footer">
        <div class="footer-link-container">
          <div class="link">Privacy Policy</div>
          <div class="dot">•</div>
          <div class="link">User Notice</div>
        </div>
        <div class="copy-right">
          @ 2021 ABugLife Studio, Inc. All rights reserved
        </div>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import SigninForm from "./SigninForm.vue";
import { RequestStatus } from '@/enum/request-status.enum';

interface SigninDto {
  email: string,
  password: string
}

export default {
  components: {
    SigninForm,
  },
  data() {
    return {
      RequestStatus,
      status: RequestStatus.Nop,
      error: null
     }
  },
  methods: {
    onSubmit: async function (dto: SigninDto) {
      try {
        this.status = RequestStatus.Loading;
        setTimeout(() => {
          this.status = RequestStatus.Error;
          this.error = 'Username or password is incorrect';
        }, 2000)
      } catch {
          this.status = RequestStatus.Error;
      }
    }
  }
};
</script>

<style lang="scss" scoped>
.page {
  @apply h-full min-h-screen relative flex items-center justify-center p-0 bg-background;

  .bg-below {
    @apply absolute top-0 left-0 w-full h-full z-10 bg-cover bg-center mix-blend-multiply;
    background-image: url(/assets/images/signin/bg2.png);
  }

  .bg-color-overlay {
    @apply absolute top-0 left-0 w-full h-full bg-primary opacity-5 z-30 mix-blend-multiply;
  }

  .page-body {
    @apply max-w-full w-full relative z-40 flex flex-col items-center min-h-screen px-4;
  }
}

.card-container {
  @apply flex-1 flex items-center w-full max-w-md mx-auto pt-4;
  @screen md {
    @apply pt-8;
  }
}

.card {
  @apply shadow-xl bg-surface py-20 px-6 z-40 rounded-lg w-full h-full flex flex-col items-center justify-center min-h-screen;

  @screen md {
    @apply h-auto min-h-0;
  }

  .card-inner {
    @apply w-full max-w-xs;
  }
}

.page-title {
  @apply text-center mb-4;

  .title {
    @apply text-on-background opacity-50;
  }
  .subtitle {
    @apply font-bold text-primary;
  }
}

.app-logo {
  @apply mb-8 bg-surface;

  .logo-img {
    @apply mx-auto h-20 w-auto mb-2 opacity-75 mix-blend-difference;
  }

  .title {
    @apply text-center text-xl font-extrabold text-on-background;
  }
}

.social-signin-container {
  & > * {
    @apply mb-2;
  }
  & > *:last-child {
    @apply mb-0;
  }
}

.footer {
  @apply flex flex-col items-center justify-center w-full px-4 py-4 sticky;
  @screen md {
    @apply px-8 py-8;
  }

  .footer-link-container {
    @apply flex items-center mb-1 space-x-4 text-sm;
    @screen md {
      @apply mb-4 text-base;
    }

    .link {
      @apply text-on-background opacity-50 cursor-pointer text-sm;
      @screen md {
        @apply text-base;
      }

      &:hover {
        @apply text-primary opacity-100;
      }
    }

    .dot {
      @apply opacity-50;
    }
  }

  .copy-right {
    @apply text-on-background opacity-25 text-center whitespace-nowrap text-sm;
    @screen md {
      @apply text-base;
    }
  }
}

.alert {
  @apply bg-error px-3 py-2 text-on-error rounded mb-3;
}
</style>

// src/examples/signin/index.tsx
/** @jsx jsx */
import { css, jsx } from '@emotion/react'
import React, { useState } from "react";
import SigninForm from "./SigninForm";
import SocialSigninButton from "./SocialSigninButton";
import { Helmet } from "react-helmet";
import { useNavigate } from 'react-router';
import { Alert } from '@material-ui/lab';
import tw from 'twin.macro';
import SeperateLineWithText from './SeperateLineWithText';

export enum RequestStatus {
    Nop = 0,
    Loading = 1,
    Success = 2,
    Error = 3,
    NoConnection = 4
}

interface SigninFormDto {
    email: string;
    password: string;
}

const SigninPage = () => {
    const navigate = useNavigate()
    const [data, setData] = useState({
        response: null,
        error: null,
        errorFields: null,
        status: RequestStatus.Nop,
    })

    const onSubmit = async (data: SigninFormDto) => {
        try {
            setData({
                response: null,
                error: null,
                errorFields: null,
                status: RequestStatus.Loading
            })
            setTimeout(() => {
                // Http Request
            }, 2000)
        } catch (error) {
            setData({
                response: null,
                error: error?.message,
                errorFields: error?.errors,
                status: RequestStatus.Error
            })
        }
        return data
    }
    const pageStyle = css`
      ${tw`h-full min-h-screen relative flex items-center justify-center p-0 bg-black`}
  
      & > .bg-below {
        ${tw`absolute top-0 left-0 w-full h-full z-10 bg-gray-50 bg-cover bg-center`}
        background-image: url(/assets/images/signin/bg1.svg);
      }
      & > .bg-upper {
        ${tw`absolute top-0 left-0 w-full h-full z-20 bg-cover bg-center`}
        background-image: url(/assets/images/signin/bg.png);
      }
  
      & > .bg-color-overlay {
        ${tw`absolute top-0 left-0 w-full h-full bg-blue-200 opacity-25 z-30`}
      }
    `

    const containerStyle = css`
      ${tw`max-w-full w-full space-y-8 relative z-40 flex items-center
  
        lg:( max-w-md )
      `}
  
      .card {
        ${tw`shadow bg-white py-12 px-6 rounded w-full h-full flex flex-col items-center justify-center min-h-screen
        
          lg:(h-auto min-h-0)
        `}
  
        .card-inner {
          ${tw`w-full max-w-xs`}
        }
      }
  
      .app-title {
        ${tw`mb-4 font-medium text-gray-600 text-center`}
      }
  
      .app-logo {
        ${tw`mb-8`}
  
        img {
          ${tw`mx-auto h-20 w-auto mb-2`}
        }
  
        .title {
          ${tw`text-center text-xl font-extrabold text-gray-700`}
        }
      }
  
      .app-form {
        ${tw`mb-10`}
      }
  
      .social-button-container {
        & > * {
          ${tw`mb-2`}
        }
        & > *:last-child {
          ${tw`mb-0`}
        }
      }
    `

    const pageTitleStyle = css`
      ${tw`text-center mb-4`}
  
      .title {
        ${tw`text-gray-600`}
      }
      .subtitle {
        ${tw`font-bold text-gray-700`}
      }
    `
    return (
        <React.Fragment>
            <Helmet>
                <title>SignIn Page</title>
            </Helmet>
            <div css={pageStyle}>
                <div className="bg-below"></div>
                <div className="bg-upper"></div>
                <div className="bg-color-overlay"></div>
                <div css={containerStyle}>
                    <div className="card">
                        <div className="card-inner">
                            <div className="app-logo">
                                <img
                                    src="/assets/images/signin/logo-black.png"
                                />

                                <h2 className="title">ABugLife Studio</h2>
                            </div>

                            <div css={pageTitleStyle}>
                                <div className="title">
                                    Signin to:
                                </div>
                                <div className="subtitle">
                                    Accounting
                                </div>
                            </div>

                            <div className="app-form">
                                {data.error && <Alert severity="error" className="mb-2">{data.error}</Alert>}
                                <SigninForm message="Sign up" onSubmit={onSubmit}></SigninForm>
                            </div>

                            <SeperateLineWithText text="OR" />

                            <div className="social-button-container">
                                <SocialSigninButton
                                    text="Signin with Google"
                                    logo="/assets/images/social/google.png"
                                    type="button"
                                />

                                <SocialSigninButton
                                    text="Signin with Line"
                                    logo="/assets/images/social/line.png"
                                    type="button"
                                />

                                <SocialSigninButton
                                    text="Signin with Microsoft"
                                    logo="/assets/images/social/microsoft.png"
                                    type="button"
                                />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </React.Fragment>
    );
};

export default SigninPage;
