// snippets/vue/src/pages/signin/Signin.vue
<template>
  <div class="page">
    <div class="bg-below"></div>
    <div class="bg-color-overlay"></div>
    <div class="page-body">
      <div class="card-container">
        <div class="card">
          <div class="card-inner">
            <div class="app-logo">
              <img
                class="logo-img"
                src="/assets/images/signin/logo-white.png"
              />
              <h2 class="title">ABugLife Studio</h2>
            </div>
            <div class="page-title">
              <div class="title">Signin to:</div>
              <div class="subtitle">Accounting</div>
            </div>
            <div class="alert" v-if="status === RequestStatus.Error">
              {{ error }}
            </div>
            <signin-form :status="status" @on-submit="onSubmit"/>

            <separate-line-with-text text="OR" />

            <div class="social-signin-container">
              <social-signin-button
                text="Signin with Google"
                logo="/assets/images/social/google.png"
                type="button"
              />

              <social-signin-button
                text="Signin with Line"
                logo="/assets/images/social/line.png"
                type="button"
              />

              <social-signin-button
                text="Signin with Microsoft"
                logo="/assets/images/social/microsoft.png"
                type="button"
              />
            </div>
          </div>
        </div>
      </div>
      <div class="footer">
        <div class="footer-link-container">
          <div class="link">Privacy Policy</div>
          <div class="dot">•</div>
          <div class="link">User Notice</div>
        </div>
        <div class="copy-right">
          @ 2021 ABugLife Studio, Inc. All rights reserved
        </div>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import SigninForm from "./SigninForm.vue";
import { RequestStatus } from '@/enum/request-status.enum';

interface SigninDto {
  email: string,
  password: string
}

export default {
  components: {
    SigninForm,
  },
  data() {
    return {
      RequestStatus,
      status: RequestStatus.Nop,
      error: null
     }
  },
  methods: {
    onSubmit: async function (dto: SigninDto) {
      try {
        this.status = RequestStatus.Loading;
        setTimeout(() => {
          this.status = RequestStatus.Error;
          this.error = 'Username or password is incorrect';
        }, 2000)
      } catch {
          this.status = RequestStatus.Error;
      }
    }
  }
};
</script>

<style lang="scss" scoped>
.page {
  @apply h-full min-h-screen relative flex items-center justify-center p-0 bg-background;

  .bg-below {
    @apply absolute top-0 left-0 w-full h-full z-10 bg-cover bg-center mix-blend-multiply;
    background-image: url(/assets/images/signin/bg2.png);
  }

  .bg-color-overlay {
    @apply absolute top-0 left-0 w-full h-full bg-primary opacity-5 z-30 mix-blend-multiply;
  }

  .page-body {
    @apply max-w-full w-full relative z-40 flex flex-col items-center min-h-screen px-4;
  }
}

.card-container {
  @apply flex-1 flex items-center w-full max-w-md mx-auto pt-4;
  @screen md {
    @apply pt-8;
  }
}

.card {
  @apply shadow-xl bg-surface py-20 px-6 z-40 rounded-lg w-full h-full flex flex-col items-center justify-center min-h-screen;

  @screen md {
    @apply h-auto min-h-0;
  }

  .card-inner {
    @apply w-full max-w-xs;
  }
}

.page-title {
  @apply text-center mb-4;

  .title {
    @apply text-on-background opacity-50;
  }
  .subtitle {
    @apply font-bold text-primary;
  }
}

.app-logo {
  @apply mb-8 bg-surface;

  .logo-img {
    @apply mx-auto h-20 w-auto mb-2 opacity-75 mix-blend-difference;
  }

  .title {
    @apply text-center text-xl font-extrabold text-on-background;
  }
}

.social-signin-container {
  & > * {
    @apply mb-2;
  }
  & > *:last-child {
    @apply mb-0;
  }
}

.footer {
  @apply flex flex-col items-center justify-center w-full px-4 py-4 sticky;
  @screen md {
    @apply px-8 py-8;
  }

  .footer-link-container {
    @apply flex items-center mb-1 space-x-4 text-sm;
    @screen md {
      @apply mb-4 text-base;
    }

    .link {
      @apply text-on-background opacity-50 cursor-pointer text-sm;
      @screen md {
        @apply text-base;
      }

      &:hover {
        @apply text-primary opacity-100;
      }
    }

    .dot {
      @apply opacity-50;
    }
  }

  .copy-right {
    @apply text-on-background opacity-25 text-center whitespace-nowrap text-sm;
    @screen md {
      @apply text-base;
    }
  }
}

.alert {
  @apply bg-error px-3 py-2 text-on-error rounded mb-3;
}
</style>

// src/pages/Form/Signin.tsx
import React from "react";
import { ShowCaseContainer, ShowCaseSection } from "@/pages/ShowCase/ShowCase";
import IframeResizer from "iframe-resizer-react";
import { ShowCaseFrame } from "../ShowCase/ShowCase";

const SigninPage = () => {
  return (
    <ShowCaseContainer>
      <ShowCaseSection title="Card Style" subtitle="With illustration background for any common login page / register page">
        <ShowCaseFrame reactCssModuleCode={signinCardCode} reactCssModuleStyle={signinCodeStyle}>
          <IframeResizer
            src="/#/examples/signin"
            style={{ width: "1px", minWidth: "100%" }}
          />
        </ShowCaseFrame>
      </ShowCaseSection>

      {/* <ShowCaseSection title="Split Screen" subtitle="Show content in one side with carousel style, your can swap a side you want">
        <ShowCaseFrame>
          <IframeResizer
            src="/#/examples/signin/split-screen"
            style={{ width: "1px", minWidth: "100%" }}
          />
        </ShowCaseFrame>
      </ShowCaseSection> */}

      {/* <ShowCaseSection title="Split Card" subtitle="Same as split screen plus card style">
        <ShowCaseFrame>
          <IframeResizer
            src="/#/examples/signin/split-card"
            style={{ width: "1px", minWidth: "100%" }}
          />
        </ShowCaseFrame>
      </ShowCaseSection> */}
    </ShowCaseContainer>
  );
};

const signinCodeStyle = `.appLogo {
  @apply mb-8;

  .logoImg {
    @apply mx-auto h-20 w-auto mb-2;
  }

  .title {
    @apply text-center text-xl font-extrabold text-gray-700;
  }
}

.page {
  @apply h-full min-h-screen relative flex items-center justify-center p-0 bg-black py-0;

  @screen md {
    @apply py-20;
  }

  .bgUpper {
    @apply absolute top-0 left-0 w-full h-full z-20 bg-cover bg-center;
    background-image: url(/assets/images/signin/bg.png);
  }

  .bgBelow {
    @apply absolute top-0 left-0 w-full h-full z-10 bg-gray-50 bg-cover bg-center;
    background-image: url(/assets/images/signin/bg1.svg);
  }

  .bgColorOverlay {
    @apply absolute top-0 left-0 w-full h-full bg-blue-200 opacity-25 z-30;
  }

  .pageBody {
    @apply max-w-full w-full space-y-8 relative z-40 flex items-center;
  
    @screen md {
      @apply max-w-md;
    }
  }
}

.card {
  @apply shadow bg-white py-20 px-6 z-40 rounded w-full h-full flex flex-col items-center justify-center min-h-screen;

  @screen md {
    @apply h-auto min-h-0;
  }

  .cardInner {
    @apply w-full max-w-xs;
  }
}

.pageTitle {
  @apply text-center mb-4;

  .title {
    @apply text-gray-600;
  }
  .subtitle {
    @apply font-bold text-gray-700;
  }
}

.socialSigninContainer {
  & > * {
    @apply mb-2;
  }
  & > *:last-child {
    @apply mb-0;
  }
}

.form {
  @apply mb-10
}

.errorAlert {
  @apply mb-2;
}`

const signinCardCode = `import React, { ReactNode, useState } from "react";
import SigninForm from "./SigninForm";
import SocialSigninButton from "./components/SocialSigninButton";
import { Helmet } from "react-helmet";
import { useNavigate } from "react-router";
import { Alert } from "@material-ui/lab";
import SeparateLineWithText from "./components/SeparateLineWithText";
import styles from "./SigninCard.module.scss";
import { RequestStatus } from "./enum/request.enum";

interface SigninFormDto {
  email: string;
  password: string;
}

const SigninPage = () => {
  const navigate = useNavigate();
  const [data, setData] = useState({
    response: null,
    error: null,
    errorFields: null,
    status: RequestStatus.Nop,
  });

  const onSubmit = async (data: SigninFormDto) => {
    try {
      setData({
        response: null,
        error: null,
        errorFields: null,
        status: RequestStatus.Loading,
      });
      setTimeout(() => {
        // Http Request
      }, 2000);
    } catch (error) {
      setData({
        response: null,
        error: error?.message,
        errorFields: error?.errors,
        status: RequestStatus.Error,
      });
    }
    return data;
  };

  return (
    <>
      <Helmet>
        <title>SignIn Page</title>
      </Helmet>
      <PageContainer>
        <CardContainer>
          <AppLogo />
          <PageTitle />
          <AppFormContainer>
            {data.error && (
              <Alert severity="error" className={styles.errorAlert}>
                {data.error}
              </Alert>
            )}
            <SigninForm message="Sign up" onSubmit={onSubmit}></SigninForm>
          </AppFormContainer>

          <SeparateLineWithText text="OR" />
          <SocialSignin />
        </CardContainer>
      </PageContainer>
    </>
  );
};

interface AppFormContainerProps {
  children: ReactNode;
}

const AppFormContainer = ({ children }: AppFormContainerProps) => {
  return <div className={styles.form}>{children}</div>;
};

const PageTitle = () => {
  return (
    <div className={styles.pageTitle}>
      <div className={styles.title}>Signin to:</div>
      <div className={styles.subtitle}>Accounting</div>
    </div>
  );
};

const AppLogo = () => {
  return (
    <div className={styles.appLogo}>
      <img
        className={styles.logoImg}
        src="/assets/images/signin/logo-black.png"
      />
      <h2 className={styles.title}>ABugLife Studio</h2>
    </div>
  );
};

interface PageContainerProps {
  children: ReactNode;
}
const PageContainer = ({ children }: PageContainerProps) => {
  return (
    <div className={styles.page}>
      <div className={styles.bgBelow}></div>
      <div className={styles.bgUpper}></div>
      <div className={styles.bgColorOverlay}></div>
      <div className={styles.pageBody}>{children}</div>
    </div>
  );
};

interface CardContainerProps {
  children: ReactNode;
}
const CardContainer = ({ children }: CardContainerProps) => {
  return (
    <div className={styles.card}>
      <div className={styles.cardInner}>{children}</div>
    </div>
  );
};

const SocialSignin = () => {
  return (
    <div className={styles.socialSigninContainer}>
      <SocialSigninButton
        text="Signin with Google"
        logo="/assets/images/social/google.png"
        type="button"
      />

      <SocialSigninButton
        text="Signin with Line"
        logo="/assets/images/social/line.png"
        type="button"
      />

      <SocialSigninButton
        text="Signin with Microsoft"
        logo="/assets/images/social/microsoft.png"
        type="button"
      />
    </div>
  );
};

export default SigninPage;`

export default SigninPage;
